//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XGame.UI
{
    using UnityEngine;
    using UnityEngine.UI;
    using System;
    using Assets.YFramework.UI;
    
    
    public class TestUIPanel : UGUIBase
    {
        
        public TestUIView root;
        
        public TestUIPanel()
        {
            setAssetsPath("Prefabs/UI/TestUI");
        }
        
        protected override void onInit()
        {
            root = panelGameObject.GetComponent<TestUIView>();
            base.onInit();
        }
        
        protected override void onShow()
        {
            base.onShow();
        }
        
        protected override void onHide()
        {
            base.onHide();
        }
        
        protected override void onEvent()
        {
            base.onEvent();
        }
        
        protected override void offEvent()
        {
            base.offEvent();
        }
    }
}
